### ISSUE TITLE
编译相关问题

### ISSUE THREAD

**Issue by Alvazz** [YummyLau/AndroidModularArchiteture#4]
编译后只产生了  玩Android， 其他的组件如何编译啊？

**Comment by Alvazz** [comment]
```
//组件调试声明
    debug {

        //调试模块，随意在当前项目新建一个module用于调试即可
        targetModuleName 'debugModule'

        //申明调试模块运行时链接组件的资源，表明运行 debugModule 时使用目录资源
        targetDebugName 'cBlog'   //这里我改成了cBlog，好像是编译出了 博文这个apk，但是运行就报错

        configuration {

            //component 调试
            'cBlog' {
                dependencies {
                    implementation component(':compBlog')
                }
            }
```


第四行注释那里，我改了下，但是运行起来会报错：

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.component.debug.cBlog, PID: 14780
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.component.debug.cBlog/com.debug.component.blog.TestActivity}: android.view.InflateException: Binary XML file line #2 in com.component.debug.cBlog:layout/blog_holder_article_layout: Binary XML file line #2 in com.component.debug.cBlog:layout/blog_holder_article_layout: Error inflating class androidx.cardview.widget.CardView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.InflateException: Binary XML file line #2 in com.component.debug.cBlog:layout/blog_holder_article_layout: Binary XML file line #2 in com.component.debug.cBlog:layout/blog_holder_article_layout: Error inflating class androidx.cardview.widget.CardView
     Caused by: android.view.InflateException: Binary XML file line #2 in com.component.debug.cBlog:layout/blog_holder_article_layout: Error inflating class androidx.cardview.widget.CardView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at com.effective.android.base.activity.BaseActivity.onCreate(BaseActivity.kt:23)
        at com.debug.DebugActivity.onCreate(DebugActivity.kt:17)
        at com.debug.component.blog.TestActivity.onCreate(TestActivity.kt:16)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 5 to dimension: type=0x1
        at android.content.res.TypedArray.getDimension(TypedArray.java:689)
        at androidx.cardview.widget.CardView.<init>(CardView.java:143)
        at androidx.cardview.widget.CardView.<init>(CardView.java:117)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:854) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481) 
        at com.effective.android.base.activity.BaseActivity.onCreate(BaseActivity.kt:23) 
        at com.debug.DebugActivity.onCreate(DebugActivity.kt:17) 
        at com.debug.component.blog.TestActivity.onCreate(TestActivity.kt:16) 
        at android.app.Activity.performCreate(Activity.java:7802) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
I/Process: Sending signal. PID: 14780 SIG: 9
Process 14780 terminated.
```

**Comment by YummyLau** [comment]
我这里可以运行的。
看log是xml报错，而且是androidx的CardView初始化。你clean下你的IDE或者module就好了

**Comment by YummyLau** [comment]
有一个tip可以保证每次run 不同的app不受缓存影响。
可以选择debugModule作为运行入口，然后点击 ”Edit Configurations“。
Android app 选择 “debugModule”，右侧选择 “Debugger”
然后在“Debugger”的tab下 “before launch：Gradle-aware Make”中点击  “+”
选择 “Gradle-aware Make”，弹窗中Task填写 ”debugModule:clean“ 来新增一个构建任务，
然后选中这个任务点击点击⏫调整到最前面就好了。

**Comment by Alvazz** [comment]
好的，我试试。谢谢啦

**Comment by YummyLau** [comment]
好的，有问题随时联系。

**Comment by Alvazz** [comment]
按照你的方法试过了，还是有这个问题

**Comment by Alvazz** [comment]
真机上也试过，也是崩溃，我只编译了cProject这个模块。

**Comment by Alvazz** [comment]
12/09 16:26:50: Launching 'debugModule' on Xiaomi Redmi Note 7.
$ adb shell am start -n "com.component.debug.cProject/com.debug.component.project.TestActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Waiting for process to come online...
Device xiaomi-redmi_note_7-e355ded4 disconnected, monitoring stopped.

**Comment by YummyLau** [comment]
加我微信吧。 pursuit_of_720. 应该是你设备或者版本问题。 微信提供一些更具体的信息给我

**Comment by Alvazz** [comment]
@YummyLau 好的，赶紧删了微信号，暴露隐私，不好！我知道了就行：D：D

**Comment by YummyLau** [comment]
@Alvazz 无妨。   问题已解决。 issue done
